const long LOOP_INTERVALO_MS = 100;

const long LOOP_CONTROLE_POSICAO = 10;
const long LOOP_CONTROLE_TEMPERATURA = 600;

const int ESTADO_INDEFINIDO = -1;
const int ESTADO_CONTROLE_POSICAO = 1;
const int ESTADO_CONTROLE_TEMPERATURA = 2;