#define PINO_INDICADOR_BUZZER 47
#define PINO_INDICADOR_BOM 49
#define PINO_INDICADOR_ALARME 51
#define PINO_INDICADOR_EMERGENCIA 53

#define INDICADOR_ATIVADO LOW
#define INDICADOR_DESATIVADO HIGH

void LimparIndicadores()
{
    digitalWrite(PINO_INDICADOR_BUZZER, INDICADOR_DESATIVADO);
    digitalWrite(PINO_INDICADOR_BOM, INDICADOR_DESATIVADO);
    digitalWrite(PINO_INDICADOR_ALARME, INDICADOR_DESATIVADO);
    digitalWrite(PINO_INDICADOR_EMERGENCIA, INDICADOR_DESATIVADO);
}

void AtivarIndicadorBom()
{
    digitalWrite(PINO_INDICADOR_BUZZER, INDICADOR_DESATIVADO);
    digitalWrite(PINO_INDICADOR_BOM, INDICADOR_ATIVADO);
    digitalWrite(PINO_INDICADOR_ALARME, INDICADOR_DESATIVADO);
    digitalWrite(PINO_INDICADOR_EMERGENCIA, INDICADOR_DESATIVADO);
}

void AtivarIndicadorAlarm()
{
    digitalWrite(PINO_INDICADOR_BUZZER, INDICADOR_DESATIVADO);
    digitalWrite(PINO_INDICADOR_BOM, INDICADOR_DESATIVADO);
    digitalWrite(PINO_INDICADOR_ALARME, INDICADOR_ATIVADO);
    digitalWrite(PINO_INDICADOR_EMERGENCIA, INDICADOR_DESATIVADO);
}

void AtivarIndicadorEmergencia()
{
    digitalWrite(PINO_INDICADOR_BUZZER, INDICADOR_ATIVADO);
    digitalWrite(PINO_INDICADOR_BOM, INDICADOR_DESATIVADO);
    digitalWrite(PINO_INDICADOR_ALARME, INDICADOR_DESATIVADO);
    digitalWrite(PINO_INDICADOR_EMERGENCIA, INDICADOR_ATIVADO);
}

void InicializarControladorDeIndicadores()
{
    pinMode(PINO_INDICADOR_BUZZER, OUTPUT);
    pinMode(PINO_INDICADOR_BOM, OUTPUT);
    pinMode(PINO_INDICADOR_ALARME, OUTPUT);
    pinMode(PINO_INDICADOR_EMERGENCIA, OUTPUT);

    LimparIndicadores();
}